server:
  port: 8082

spring:
  kafka:
    consumer:
      group-id: group-2
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
logging:
  level:
    root: info